// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | AuthorBoxSlice
  | MostReadArticlesSlice
  | LatestArticlesSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Item in *Artigo → Itens*
 */
export interface ArticleDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Artigo → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Artigo → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Artigo documents
 */
interface ArticleDocumentData {
  /**
   * Autor field in *Artigo*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Categoria field in *Artigo*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"article_category">;

  /**
   * Imagem field in *Artigo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Artigo*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Artigo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;

  /**
   * Tempo de Leitura field in *Artigo*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: article.reading_time
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  reading_time: prismic.NumberField /**
   * Itens field in *Artigo*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<ArticleDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Artigo document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type ArticleCategoriesDocumentDataSlicesSlice =
  | MostReadArticlesSlice
  | AuthorBoxSlice
  | CallToActionSlice
  | FaqSlice
  | LatestArticlesSlice
  | ContentBlockSlice;

/**
 * Item in *Categorias de Artigos → Itens*
 */
export interface ArticleCategoriesDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Categorias de Artigos → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_categories.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Categorias de Artigos → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_categories.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Categorias de Artigos documents
 */
interface ArticleCategoriesDocumentData {
  /**
   * Slice Zone field in *Categorias de Artigos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_categories.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleCategoriesDocumentDataSlicesSlice> /**
   * Meta Title field in *Categorias de Artigos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article_categories.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Categorias de Artigos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article_categories.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Categorias de Artigos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_categories.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Categorias de Artigos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_categories.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField /**
   * Itens field in *Categorias de Artigos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_categories.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<ArticleCategoriesDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Categorias de Artigos document from Prismic
 *
 * - **API ID**: `article_categories`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleCategoriesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticleCategoriesDocumentData>,
    "article_categories",
    Lang
  >;

type ArticleCategoryDocumentDataSlicesSlice =
  | MostReadArticlesSlice
  | ContentBlockSlice
  | LatestArticlesSlice
  | FaqSlice
  | CallToActionSlice
  | AuthorBoxSlice;

/**
 * Item in *Categoria de Artigo → Itens*
 */
export interface ArticleCategoryDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Categoria de Artigo → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Categoria de Artigo → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Categoria de Artigo documents
 */
interface ArticleCategoryDocumentData {
  /**
   * Nome field in *Categoria de Artigo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Slice Zone field in *Categoria de Artigo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleCategoryDocumentDataSlicesSlice> /**
   * Meta Title field in *Categoria de Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article_category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Categoria de Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article_category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Categoria de Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_category.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Categoria de Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_category.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField /**
   * Itens field in *Categoria de Artigo*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<ArticleCategoryDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Categoria de Artigo document from Prismic
 *
 * - **API ID**: `article_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleCategoryDocumentData>,
    "article_category",
    Lang
  >;

type ArticlesDocumentDataSlicesSlice =
  | AuthorBoxSlice
  | MostReadArticlesSlice
  | LatestArticlesSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Item in *Artigos → Itens*
 */
export interface ArticlesDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Artigos → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Artigos → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Artigos documents
 */
interface ArticlesDocumentData {
  /**
   * Slice Zone field in *Artigos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticlesDocumentDataSlicesSlice> /**
   * Meta Title field in *Artigos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articles.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artigos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articles.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Artigos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: articles.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Artigos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: articles.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField /**
   * Itens field in *Artigos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: articles.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<ArticlesDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Artigos document from Prismic
 *
 * - **API ID**: `articles`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticlesDocumentData>,
    "articles",
    Lang
  >;

/**
 * Item in *Autor → Redes Sociais*
 */
export interface AuthorDocumentDataSocialNetworksItem {
  /**
   * Rede Social field in *Autor → Redes Sociais*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<
    "Facebook" | "Email" | "LinkedIn" | "Instagram" | "YouTube"
  >;

  /**
   * Link field in *Autor → Redes Sociais*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type AuthorDocumentDataSlicesSlice =
  | AuthorBoxSlice
  | LatestArticlesSlice
  | MostReadArticlesSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Item in *Autor → Itens*
 */
export interface AuthorDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Autor → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Autor → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Autor documents
 */
interface AuthorDocumentData {
  /**
   * Avatar field in *Autor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Name field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Cargo field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Bio field in *Autor*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Redes Sociais field in *Autor*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_networks: prismic.GroupField<
    Simplify<AuthorDocumentDataSocialNetworksItem>
  >;

  /**
   * Slice Zone field in *Autor*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: author.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AuthorDocumentDataSlicesSlice> /**
   * Meta Title field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: author.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: author.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Autor*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: author.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Autor*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: author.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField /**
   * Itens field in *Autor*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: author.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<AuthorDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Autor document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type AuthorsDocumentDataSlicesSlice =
  | AuthorBoxSlice
  | FaqSlice
  | ContentBlockSlice
  | MostReadArticlesSlice
  | LatestArticlesSlice
  | CallToActionSlice;

/**
 * Item in *Autores → Itens*
 */
export interface AuthorsDocumentDataBreadcrumbItemsItem {
  /**
   * Label field in *Autores → Itens*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.breadcrumb_items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Autores → Itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.breadcrumb_items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Autores documents
 */
interface AuthorsDocumentData {
  /**
   * Slice Zone field in *Autores*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AuthorsDocumentDataSlicesSlice> /**
   * Meta Title field in *Autores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: authors.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Autores*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: authors.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Autores*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: authors.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Autores*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: authors.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField /**
   * Itens field in *Autores*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: authors.breadcrumb_items[]
   * - **Tab**: Breadcrumb
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  breadcrumb_items: prismic.GroupField<
    Simplify<AuthorsDocumentDataBreadcrumbItemsItem>
  >;
}

/**
 * Autores document from Prismic
 *
 * - **API ID**: `authors`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AuthorsDocumentData>,
    "authors",
    Lang
  >;

/**
 * Content for CallToAction documents
 */
interface CallToActionDocumentData {
  /**
   * Conteúdo field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * CTA Label field in *CallToAction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *CallToAction*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * CallToAction document from Prismic
 *
 * - **API ID**: `call_to_action`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CallToActionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CallToActionDocumentData>,
    "call_to_action",
    Lang
  >;

/**
 * Item in *Faq → Perguntas Frequentes*
 */
export interface FaqDocumentDataFrequentlyAskedQuestionsItem {
  /**
   * Pergunta field in *Faq → Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Resposta field in *Faq → Perguntas Frequentes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Content for Faq documents
 */
interface FaqDocumentData {
  /**
   * Título field in *Faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Perguntas Frequentes field in *Faq*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  frequently_asked_questions: prismic.GroupField<
    Simplify<FaqDocumentDataFrequentlyAskedQuestionsItem>
  >;
}

/**
 * Faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

type FooterDocumentDataSlicesSlice = FooterLinksSlice;

/**
 * Item in *Footer → Números da ANS*
 */
export interface FooterDocumentDataAnsNumberItem {
  /**
   * Nome field in *Footer → Números da ANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Número field in *Footer → Números da ANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Números da ANS field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[]
   * - **Tab**: ANS
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ans_number: prismic.GroupField<Simplify<FooterDocumentDataAnsNumberItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

interface HeaderDocumentData {}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | AuthorBoxSlice
  | LatestArticlesSlice
  | MostReadArticlesSlice
  | CallToActionSlice
  | ContentBlockSlice
  | FaqSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Layout → Meta Tags*
 */
export interface LayoutDocumentDataMetaTagsItem {
  /**
   * Propriedade field in *Layout → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[].property
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property: prismic.KeyTextField;

  /**
   * Conteúdo field in *Layout → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Meta Tags field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  meta_tags: prismic.GroupField<Simplify<LayoutDocumentDataMetaTagsItem>>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

/**
 * Item in *Artigos mais lidos → Artigos*
 */
export interface MostReadArticlesDocumentDataArticlesItem {
  /**
   * Artigo field in *Artigos mais lidos → Artigos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.articles[].article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.ContentRelationshipField<"article">;
}

/**
 * Content for Artigos mais lidos documents
 */
interface MostReadArticlesDocumentData {
  /**
   * Título field in *Artigos mais lidos*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.TitleField;

  /**
   * Artigos field in *Artigos mais lidos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.articles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<MostReadArticlesDocumentDataArticlesItem>
  >;
}

/**
 * Artigos mais lidos document from Prismic
 *
 * - **API ID**: `most_read_articles`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MostReadArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MostReadArticlesDocumentData>,
    "most_read_articles",
    Lang
  >;

type OperatorDocumentDataSlicesSlice =
  | FaqSlice
  | LatestArticlesSlice
  | MostReadArticlesSlice
  | ContentBlockSlice
  | CallToActionSlice
  | AuthorBoxSlice;

/**
 * Content for Operadora documents
 */
interface OperatorDocumentData {
  /**
   * Slice Zone field in *Operadora*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OperatorDocumentDataSlicesSlice> /**
   * Meta Description field in *Operadora*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: operator.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Operadora*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Operadora*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: operator.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Operadora document from Prismic
 *
 * - **API ID**: `operator`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OperatorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OperatorDocumentData>,
    "operator",
    Lang
  >;

/**
 * Item in *Redirects → Redirecionamentos*
 */
export interface RedirectsDocumentDataRedirectsItem {
  /**
   * Origem field in *Redirects → Redirecionamentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].origin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  origin: prismic.KeyTextField;

  /**
   * Destino field in *Redirects → Redirecionamentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].destination
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;

  /**
   * Permanente field in *Redirects → Redirecionamentos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: redirects.redirects[].permanent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  permanent: prismic.BooleanField;
}

/**
 * Content for Redirects documents
 */
interface RedirectsDocumentData {
  /**
   * Redirecionamentos field in *Redirects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redirects: prismic.GroupField<Simplify<RedirectsDocumentDataRedirectsItem>>;
}

/**
 * Redirects document from Prismic
 *
 * - **API ID**: `redirects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectsDocumentData>,
    "redirects",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | ArticleCategoriesDocument
  | ArticleCategoryDocument
  | ArticlesDocument
  | AuthorDocument
  | AuthorsDocument
  | CallToActionDocument
  | FaqDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LayoutDocument
  | MostReadArticlesDocument
  | OperatorDocument
  | RedirectsDocument;

/**
 * Primary content in *AuthorBox → Primary*
 */
export interface AuthorBoxSliceDefaultPrimary {
  /**
   * Autor field in *AuthorBox → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: author_box.primary.author
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;
}

/**
 * Default variation for AuthorBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AuthorBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AuthorBox*
 */
type AuthorBoxSliceVariation = AuthorBoxSliceDefault;

/**
 * AuthorBox Shared Slice
 *
 * - **API ID**: `author_box`
 * - **Description**: AuthorBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AuthorBoxSlice = prismic.SharedSlice<
  "author_box",
  AuthorBoxSliceVariation
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * CallToAction field in *CallToAction → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.ContentRelationshipField<"call_to_action">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContentBlock → Primary*
 */
export interface ContentBlockSliceDefaultPrimary {
  /**
   * Conteúdo field in *ContentBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentBlockSliceVariation = ContentBlockSliceDefault;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_block`
 * - **Description**: ContentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSlice = prismic.SharedSlice<
  "content_block",
  ContentBlockSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Faq field in *Faq → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<"faq">;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Default variation for LatestArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *LatestArticles*
 */
type LatestArticlesSliceVariation = LatestArticlesSliceDefault;

/**
 * LatestArticles Shared Slice
 *
 * - **API ID**: `latest_articles`
 * - **Description**: LatestArticles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestArticlesSlice = prismic.SharedSlice<
  "latest_articles",
  LatestArticlesSliceVariation
>;

/**
 * Primary content in *MostReadArticles → Primary*
 */
export interface MostReadArticlesSliceDefaultPrimary {
  /**
   * Artigo mais lidos field in *MostReadArticles → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.primary.most_read_articles
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  most_read_articles: prismic.ContentRelationshipField<"most_read_articles">;
}

/**
 * Default variation for MostReadArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MostReadArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MostReadArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MostReadArticles*
 */
type MostReadArticlesSliceVariation = MostReadArticlesSliceDefault;

/**
 * MostReadArticles Shared Slice
 *
 * - **API ID**: `most_read_articles`
 * - **Description**: MostReadArticles
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MostReadArticlesSlice = prismic.SharedSlice<
  "most_read_articles",
  MostReadArticlesSliceVariation
>;

/**
 * Primary content in *FooterLinks → Items*
 */
export interface FooterLinksSliceDefaultItem {
  /**
   * Título da Coluna field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].column_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  column_title: prismic.RichTextField;

  /**
   * Links field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].links
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  links: prismic.RichTextField;
}

/**
 * Default variation for FooterLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FooterLinksSliceDefaultItem>
>;

/**
 * Slice variation for *FooterLinks*
 */
type FooterLinksSliceVariation = FooterLinksSliceDefault;

/**
 * FooterLinks Shared Slice
 *
 * - **API ID**: `footer_links`
 * - **Description**: FooterLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSlice = prismic.SharedSlice<
  "footer_links",
  FooterLinksSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      ArticleDocumentDataBreadcrumbItemsItem,
      ArticleCategoriesDocument,
      ArticleCategoriesDocumentData,
      ArticleCategoriesDocumentDataSlicesSlice,
      ArticleCategoriesDocumentDataBreadcrumbItemsItem,
      ArticleCategoryDocument,
      ArticleCategoryDocumentData,
      ArticleCategoryDocumentDataSlicesSlice,
      ArticleCategoryDocumentDataBreadcrumbItemsItem,
      ArticlesDocument,
      ArticlesDocumentData,
      ArticlesDocumentDataSlicesSlice,
      ArticlesDocumentDataBreadcrumbItemsItem,
      AuthorDocument,
      AuthorDocumentData,
      AuthorDocumentDataSocialNetworksItem,
      AuthorDocumentDataSlicesSlice,
      AuthorDocumentDataBreadcrumbItemsItem,
      AuthorsDocument,
      AuthorsDocumentData,
      AuthorsDocumentDataSlicesSlice,
      AuthorsDocumentDataBreadcrumbItemsItem,
      CallToActionDocument,
      CallToActionDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataFrequentlyAskedQuestionsItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocumentDataAnsNumberItem,
      HeaderDocument,
      HeaderDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataMetaTagsItem,
      MostReadArticlesDocument,
      MostReadArticlesDocumentData,
      MostReadArticlesDocumentDataArticlesItem,
      OperatorDocument,
      OperatorDocumentData,
      OperatorDocumentDataSlicesSlice,
      RedirectsDocument,
      RedirectsDocumentData,
      RedirectsDocumentDataRedirectsItem,
      AllDocumentTypes,
      AuthorBoxSlice,
      AuthorBoxSliceDefaultPrimary,
      AuthorBoxSliceVariation,
      AuthorBoxSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContentBlockSlice,
      ContentBlockSliceDefaultPrimary,
      ContentBlockSliceVariation,
      ContentBlockSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      LatestArticlesSlice,
      LatestArticlesSliceVariation,
      LatestArticlesSliceDefault,
      MostReadArticlesSlice,
      MostReadArticlesSliceDefaultPrimary,
      MostReadArticlesSliceVariation,
      MostReadArticlesSliceDefault,
      FooterLinksSlice,
      FooterLinksSliceDefaultItem,
      FooterLinksSliceVariation,
      FooterLinksSliceDefault,
    };
  }
}
