// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | InfoCardsSlice
  | TableSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Content for Artigo documents
 */
interface ArticleDocumentData {
  /**
   * Título field in *Artigo*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Autor field in *Artigo*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  author: prismic.ContentRelationshipField<"author">;

  /**
   * Categoria field in *Artigo*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"article_category">;

  /**
   * Imagem field in *Artigo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Artigo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;

  /**
   * Tempo de Leitura field in *Artigo*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: article.reading_time
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  reading_time: prismic.NumberField;
}

/**
 * Artigo document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type ArticleCategoryDocumentDataSlicesSlice =
  | InfoCardsSlice
  | BannerSlice
  | TableSlice
  | ContentBlockSlice
  | FaqSlice
  | CallToActionSlice;

/**
 * Content for Categoria de Artigo documents
 */
interface ArticleCategoryDocumentData {
  /**
   * Nome field in *Categoria de Artigo*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Ícone field in *Categoria de Artigo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.icone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Categoria de Artigo*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_category.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleCategoryDocumentDataSlicesSlice> /**
   * Meta Title field in *Categoria de Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article_category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Categoria de Artigo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article_category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Categoria de Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_category.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Categoria de Artigo*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: article_category.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Categoria de Artigo document from Prismic
 *
 * - **API ID**: `article_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleCategoryDocumentData>,
    "article_category",
    Lang
  >;

/**
 * Item in *Autor(a) → Redes Sociais*
 */
export interface AuthorDocumentDataSocialNetworksItem {
  /**
   * Rede Social field in *Autor(a) → Redes Sociais*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[].name
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  name: prismic.SelectField<
    "Facebook" | "Email" | "LinkedIn" | "Instagram" | "YouTube"
  >;

  /**
   * Link field in *Autor(a) → Redes Sociais*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type AuthorDocumentDataSlicesSlice =
  | BannerSlice
  | InfoCardsSlice
  | TableSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Content for Autor(a) documents
 */
interface AuthorDocumentData {
  /**
   * Nome field in *Autor(a)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Avatar field in *Autor(a)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.avatar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Bio field in *Autor(a)*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Empresa field in *Autor(a)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company: prismic.KeyTextField;

  /**
   * Cargo field in *Autor(a)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Redes Sociais field in *Autor(a)*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: author.social_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_networks: prismic.GroupField<
    Simplify<AuthorDocumentDataSocialNetworksItem>
  >;

  /**
   * Slice Zone field in *Autor(a)*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: author.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AuthorDocumentDataSlicesSlice> /**
   * Meta Title field in *Autor(a)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: author.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Autor(a)*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: author.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Autor(a)*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: author.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Autor(a)*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: author.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Autor(a) document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

type BlogDocumentDataSlicesSlice =
  | TableSlice
  | InfoCardsSlice
  | BannerSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Blog*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Blog*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: blog.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Content for CallToAction documents
 */
interface CallToActionDocumentData {
  /**
   * Conteúdo field in *CallToAction*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * CTA Label field in *CallToAction*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *CallToAction*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * CallToAction document from Prismic
 *
 * - **API ID**: `call_to_action`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CallToActionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CallToActionDocumentData>,
    "call_to_action",
    Lang
  >;

/**
 * Item in *Faq → Perguntas Frequentes*
 */
export interface FaqDocumentDataFrequentlyAskedQuestionsItem {
  /**
   * Pergunta field in *Faq → Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Resposta field in *Faq → Perguntas Frequentes*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;
}

/**
 * Content for Faq documents
 */
interface FaqDocumentData {
  /**
   * Título field in *Faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Perguntas Frequentes field in *Faq*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.frequently_asked_questions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  frequently_asked_questions: prismic.GroupField<
    Simplify<FaqDocumentDataFrequentlyAskedQuestionsItem>
  >;
}

/**
 * Faq document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;

type FooterDocumentDataSlicesSlice = FooterLinksSlice;

/**
 * Item in *Footer → Números da ANS*
 */
export interface FooterDocumentDataAnsNumberItem {
  /**
   * Nome field in *Footer → Números da ANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Número field in *Footer → Números da ANS*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice> /**
   * Números da ANS field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ans_number[]
   * - **Tab**: ANS
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  ans_number: prismic.GroupField<Simplify<FooterDocumentDataAnsNumberItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = MenuItemSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | TableSlice
  | BannerSlice
  | InfoCardsSlice
  | CallToActionSlice
  | ContentBlockSlice
  | FaqSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Layout Principal → Meta Tags*
 */
export interface LayoutDocumentDataMetaTagsItem {
  /**
   * Propriedade field in *Layout Principal → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[].property
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  property: prismic.KeyTextField;

  /**
   * Conteúdo field in *Layout Principal → Meta Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Content for Layout Principal documents
 */
interface LayoutDocumentData {
  /**
   * Meta Tags field in *Layout Principal*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.meta_tags[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  meta_tags: prismic.GroupField<Simplify<LayoutDocumentDataMetaTagsItem>>;
}

/**
 * Layout Principal document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

/**
 * Item in *Artigos mais lidos → Artigos*
 */
export interface MostReadArticlesDocumentDataArticlesItem {
  /**
   * Artigo field in *Artigos mais lidos → Artigos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.articles[].article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.ContentRelationshipField;
}

/**
 * Content for Artigos mais lidos documents
 */
interface MostReadArticlesDocumentData {
  /**
   * Título field in *Artigos mais lidos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Artigos field in *Artigos mais lidos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: most_read_articles.articles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articles: prismic.GroupField<
    Simplify<MostReadArticlesDocumentDataArticlesItem>
  >;
}

/**
 * Artigos mais lidos document from Prismic
 *
 * - **API ID**: `most_read_articles`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MostReadArticlesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MostReadArticlesDocumentData>,
    "most_read_articles",
    Lang
  >;

type OperatorDocumentDataSlicesSlice =
  | BannerSlice
  | TableSlice
  | InfoCardsSlice
  | FaqSlice
  | ContentBlockSlice
  | CallToActionSlice;

/**
 * Content for Operadora documents
 */
interface OperatorDocumentData {
  /**
   * Nome field in *Operadora*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Logo field in *Operadora*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Operadora*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OperatorDocumentDataSlicesSlice> /**
   * Meta Description field in *Operadora*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: operator.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Operadora*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: operator.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Operadora*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: operator.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Operadora document from Prismic
 *
 * - **API ID**: `operator`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OperatorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OperatorDocumentData>,
    "operator",
    Lang
  >;

interface OperatorLayoutDocumentData {}

/**
 * Layout de Operadora document from Prismic
 *
 * - **API ID**: `operator_layout`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OperatorLayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OperatorLayoutDocumentData>,
    "operator_layout",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TableSlice
  | BannerSlice
  | CallToActionSlice
  | ContentBlockSlice
  | FaqSlice
  | InfoCardsSlice;

/**
 * Content for Página documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Página*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Image field in *Página*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Página*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Robots Index field in *Página*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.robots_index
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_index: prismic.BooleanField;

  /**
   * Robots Follow field in *Página*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.robots_follow
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  robots_follow: prismic.BooleanField;
}

/**
 * Página document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Redirecionamentos → Redirecionamentos*
 */
export interface RedirectsDocumentDataRedirectsItem {
  /**
   * Origem field in *Redirecionamentos → Redirecionamentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].origin
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  origin: prismic.KeyTextField;

  /**
   * Destino field in *Redirecionamentos → Redirecionamentos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[].destination
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;

  /**
   * Permanente field in *Redirecionamentos → Redirecionamentos*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: redirects.redirects[].permanent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  permanent: prismic.BooleanField;
}

/**
 * Content for Redirecionamentos documents
 */
interface RedirectsDocumentData {
  /**
   * Redirecionamentos field in *Redirecionamentos*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirects.redirects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redirects: prismic.GroupField<Simplify<RedirectsDocumentDataRedirectsItem>>;
}

/**
 * Redirecionamentos document from Prismic
 *
 * - **API ID**: `redirects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectsDocumentData>,
    "redirects",
    Lang
  >;

type TableDocumentDataSlicesSlice = TableRowSlice;

/**
 * Content for Tabela documents
 */
interface TableDocumentData {
  /**
   * Slice Zone field in *Tabela*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: table.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TableDocumentDataSlicesSlice>;
}

/**
 * Tabela document from Prismic
 *
 * - **API ID**: `table`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TableDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TableDocumentData>, "table", Lang>;

export type AllDocumentTypes =
  | ArticleDocument
  | ArticleCategoryDocument
  | AuthorDocument
  | BlogDocument
  | CallToActionDocument
  | FaqDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LayoutDocument
  | MostReadArticlesDocument
  | OperatorDocument
  | OperatorLayoutDocument
  | PageDocument
  | RedirectsDocument
  | TableDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Título field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceImagePrimary {
  /**
   * Título field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Imagem field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Com Imagem variation for Banner Slice
 *
 * - **API ID**: `image`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceImage = prismic.SharedSliceVariation<
  "image",
  Simplify<BannerSliceImagePrimary>,
  never
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceBackgroundPrimary {
  /**
   * Título field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Label field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Background field in *Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.background
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background: prismic.ImageField<never>;
}

/**
 * Com Background variation for Banner Slice
 *
 * - **API ID**: `background`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceBackground = prismic.SharedSliceVariation<
  "background",
  Simplify<BannerSliceBackgroundPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation =
  | BannerSliceDefault
  | BannerSliceImage
  | BannerSliceBackground;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * CallToAction field in *CallToAction → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.call_to_action
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action: prismic.ContentRelationshipField<"call_to_action">;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContentBlock → Primary*
 */
export interface ContentBlockSliceDefaultPrimary {
  /**
   * Conteúdo field in *ContentBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentBlockSliceVariation = ContentBlockSliceDefault;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_block`
 * - **Description**: ContentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentBlockSlice = prismic.SharedSlice<
  "content_block",
  ContentBlockSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Faq field in *Faq → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.faq
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  faq: prismic.ContentRelationshipField<"faq">;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *InfoCards → Items*
 */
export interface InfoCardsSliceDefaultItem {
  /**
   * Imagem field in *InfoCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *InfoCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *InfoCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_cards.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for InfoCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<InfoCardsSliceDefaultItem>
>;

/**
 * Slice variation for *InfoCards*
 */
type InfoCardsSliceVariation = InfoCardsSliceDefault;

/**
 * InfoCards Shared Slice
 *
 * - **API ID**: `info_cards`
 * - **Description**: InfoCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoCardsSlice = prismic.SharedSlice<
  "info_cards",
  InfoCardsSliceVariation
>;

/**
 * Primary content in *Table → Primary*
 */
export interface TableSliceDefaultPrimary {
  /**
   * Tabela field in *Table → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: table.primary.table
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  table: prismic.ContentRelationshipField<"table">;
}

/**
 * Default variation for Table Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TableSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Table*
 */
type TableSliceVariation = TableSliceDefault;

/**
 * Table Shared Slice
 *
 * - **API ID**: `table`
 * - **Description**: Table
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableSlice = prismic.SharedSlice<"table", TableSliceVariation>;

/**
 * Primary content in *TableRow → Items*
 */
export interface TableRowSliceDefaultItem {
  /**
   * Valor field in *TableRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_row.items[].value
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value: prismic.RichTextField;
}

/**
 * Head variation for TableRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TableRowSliceDefaultItem>
>;

/**
 * Primary content in *TableRow → Items*
 */
export interface TableRowSliceBodyItem {
  /**
   * Valor field in *TableRow → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_row.items[].value
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value: prismic.RichTextField;
}

/**
 * Body variation for TableRow Slice
 *
 * - **API ID**: `body`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableRowSliceBody = prismic.SharedSliceVariation<
  "body",
  Record<string, never>,
  Simplify<TableRowSliceBodyItem>
>;

/**
 * Slice variation for *TableRow*
 */
type TableRowSliceVariation = TableRowSliceDefault | TableRowSliceBody;

/**
 * TableRow Shared Slice
 *
 * - **API ID**: `table_row`
 * - **Description**: TableRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableRowSlice = prismic.SharedSlice<
  "table_row",
  TableRowSliceVariation
>;

/**
 * Primary content in *MenuItem → Primary*
 */
export interface MenuItemSliceDefaultPrimary {
  /**
   * Item Label field in *MenuItem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.item_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_label: prismic.KeyTextField;

  /**
   * Item Link field in *MenuItem → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.primary.item_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item_link: prismic.LinkField;
}

/**
 * Primary content in *MenuItem → Items*
 */
export interface MenuItemSliceDefaultItem {
  /**
   * SubItem Label field in *MenuItem → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].subitem_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subitem_label: prismic.KeyTextField;

  /**
   * SubItem Link field in *MenuItem → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu_item.items[].subitem_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subitem_link: prismic.LinkField;
}

/**
 * Default variation for MenuItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuItemSliceDefaultPrimary>,
  Simplify<MenuItemSliceDefaultItem>
>;

/**
 * Slice variation for *MenuItem*
 */
type MenuItemSliceVariation = MenuItemSliceDefault;

/**
 * MenuItem Shared Slice
 *
 * - **API ID**: `menu_item`
 * - **Description**: MenuItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuItemSlice = prismic.SharedSlice<
  "menu_item",
  MenuItemSliceVariation
>;

/**
 * Primary content in *FooterLinks → Items*
 */
export interface FooterLinksSliceDefaultItem {
  /**
   * Título da Coluna field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].column_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  column_title: prismic.RichTextField;

  /**
   * Links field in *FooterLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_links.items[].links
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  links: prismic.RichTextField;
}

/**
 * Default variation for FooterLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FooterLinksSliceDefaultItem>
>;

/**
 * Slice variation for *FooterLinks*
 */
type FooterLinksSliceVariation = FooterLinksSliceDefault;

/**
 * FooterLinks Shared Slice
 *
 * - **API ID**: `footer_links`
 * - **Description**: FooterLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterLinksSlice = prismic.SharedSlice<
  "footer_links",
  FooterLinksSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      ArticleCategoryDocument,
      ArticleCategoryDocumentData,
      ArticleCategoryDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      AuthorDocumentDataSocialNetworksItem,
      AuthorDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      CallToActionDocument,
      CallToActionDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataFrequentlyAskedQuestionsItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      FooterDocumentDataAnsNumberItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataMetaTagsItem,
      MostReadArticlesDocument,
      MostReadArticlesDocumentData,
      MostReadArticlesDocumentDataArticlesItem,
      OperatorDocument,
      OperatorDocumentData,
      OperatorDocumentDataSlicesSlice,
      OperatorLayoutDocument,
      OperatorLayoutDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      RedirectsDocument,
      RedirectsDocumentData,
      RedirectsDocumentDataRedirectsItem,
      TableDocument,
      TableDocumentData,
      TableDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceImagePrimary,
      BannerSliceBackgroundPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BannerSliceImage,
      BannerSliceBackground,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContentBlockSlice,
      ContentBlockSliceDefaultPrimary,
      ContentBlockSliceVariation,
      ContentBlockSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      InfoCardsSlice,
      InfoCardsSliceDefaultItem,
      InfoCardsSliceVariation,
      InfoCardsSliceDefault,
      TableSlice,
      TableSliceDefaultPrimary,
      TableSliceVariation,
      TableSliceDefault,
      TableRowSlice,
      TableRowSliceDefaultItem,
      TableRowSliceBodyItem,
      TableRowSliceVariation,
      TableRowSliceDefault,
      TableRowSliceBody,
      MenuItemSlice,
      MenuItemSliceDefaultPrimary,
      MenuItemSliceDefaultItem,
      MenuItemSliceVariation,
      MenuItemSliceDefault,
      FooterLinksSlice,
      FooterLinksSliceDefaultItem,
      FooterLinksSliceVariation,
      FooterLinksSliceDefault,
    };
  }
}
