import {
	IconBrandFacebook,
	IconBrandInstagram,
	IconBrandLinkedin,
	IconBrandWhatsapp,
	IconBrandX,
	IconBrandYoutube,
	IconBuildingEstate,
	IconCalendar,
	IconDeviceLaptop,
	IconDeviceMobile,
	IconDeviceTablet,
	IconDeviceTv,
	IconDownload,
	IconFileText,
	IconHeadset,
	IconHelp,
	IconHome,
	IconHomeSignal,
	IconMapPin,
	IconMessages,
	IconNetwork,
	IconNews,
	IconPdf,
	IconPhone,
	IconSquareCheck,
	IconTool,
	IconUpload,
	IconWifi
} from '@tabler/icons-react'

export const CMS_ICONS = {
	Check: IconSquareCheck,
	Download: IconDownload,
	Instalaçao: IconHomeSignal,
	Internet: IconNetwork,
	Smartphone: IconDeviceMobile,
	Suporte: IconHeadset,
	Telefone: IconPhone,
	Upload: IconUpload,
	'Wi-Fi': IconWifi,
	Ajuda: IconHelp,
	Arquivo: IconFileText,
	Calendário: IconCalendar,
	Headset: IconHeadset,
	Instalação: IconHomeSignal,
	Jornal: IconNews,
	Laptop: IconDeviceLaptop,
	Tablet: IconDeviceTablet,
	TV: IconDeviceTv,
	WhatsApp: IconBrandWhatsapp,
	Facebook: IconBrandFacebook,
	Instagram: IconBrandInstagram,
	Twitter: IconBrandX,
	Ferramenta: IconTool,
	Chat: IconMessages,
	PDF: IconPdf,
	Empresa: IconBuildingEstate,
	Localização: IconMapPin,
	YouTube: IconBrandYoutube,
	LinkedIn: IconBrandLinkedin,
	Casa: IconHome
}
