// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	banner: dynamic(() => import('./Banner')),
	call_to_action: dynamic(() => import('./CallToAction')),
	content_block: dynamic(() => import('./ContentBlock')),
	faq: dynamic(() => import('./Faq')),
	info_cards: dynamic(() => import('./InfoCards')),
	you_tube_video: dynamic(() => import('./YouTubeVideo'))
}
