// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	author_box: dynamic(() => import('./AuthorBox')),
	call_to_action: dynamic(() => import('./CallToAction')),
	content_block: dynamic(() => import('./ContentBlock')),
	faq: dynamic(() => import('./Faq')),
	latest_articles: dynamic(() => import('./LatestArticles')),
	most_read_articles: dynamic(() => import('./MostReadArticles'))
}
