// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	banner: dynamic(() => import('./Banner')),
	call_to_action: dynamic(() => import('./CallToAction')),
	content_block: dynamic(() => import('./ContentBlock')),
	faq: dynamic(() => import('./Faq')),
	footer_links: dynamic(() => import('./FooterLinks')),
	html_block: dynamic(() => import('./HtmlBlock')),
	info_cards: dynamic(() => import('./InfoCards')),
	links_card: dynamic(() => import('./LinksCard')),
	menu_item: dynamic(() => import('./MenuItem')),
	products_carousel: dynamic(() => import('./ProductsCarousel')),
	slice_group: dynamic(() => import('./SliceGroup')),
	table: dynamic(() => import('./Table'))
}
